#! /bin/bash
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_task_listing_2.0.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_job_listing_2.0.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_task_listing.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_job_listing.xml
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.2.5.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.2.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.0.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.1.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/layout/cronscheduler_task_timeline.xml
rm ./app/code/Wyomind/Core/view/frontend/layout/licensemanager_activation_webservice.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/timeline/actions.phtml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/layout/cronscheduler_task_listing.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/listing/actions.phtml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/layout/cronscheduler_job_listing.xml
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Status/Options.php
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/ActivationFlag.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/job/listing/actions.phtml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template/task/grid/status.html
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript/javascript.js
rm ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Group/Options.php
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Code/Options.php
rm ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Code/Options.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/multiplex/multiplex.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed/htmlmixed.js
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/Encrypted.php
rm ./app/code/Wyomind/Core/view/adminhtml/layout/adminhtml_system_config_edit.xml
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Job/GenerateSchedule.php
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Messages.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/timeline.phtml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/upgradeToPro.phtml
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Actions.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Status
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/timeline
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Timeline/Actions.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/listing
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template/task/grid
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Listing/Actions.php
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/MassDelete.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/job/listing
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/view.phtml
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Code
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/matchbrackets.js
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Group
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Code
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Job/Listing/Actions.php
rm ./app/code/Wyomind/CronScheduler/Model/ResourceModel/Task/Collection.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/active-line.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/autorefresh.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike/clike.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.css
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/Timeline.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/multiplex
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/Listing.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/formatting.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/fullscreen.js
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template/task
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Job/Listing.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/mdn-like.css
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/embedded.js
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/css/timeline.css
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/requirejs-config.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css/css.js
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/View.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php/php.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml/xml.js
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Timeline
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Timeline.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/css/common.css
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/js/timeline.js
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/job
rm ./app/code/Wyomind/CronScheduler/Ui/DataProvider/TaskProvider.php
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/UpgradeToPro.php
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Listing
rm ./app/code/Wyomind/CronScheduler/Console/Command/Task/Listing.php
rm ./app/code/Wyomind/Core/view/frontend/templates/webservice.phtml
rm ./app/code/Wyomind/CronScheduler/Ui/DataProvider/JobProvider.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php
rm ./app/code/Wyomind/CronScheduler/Console/Command/Job/Listing.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css
rm ./app/code/Wyomind/Core/Observer/ControllerActionPredispatch.php
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Job/Listing
rmdir  ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/js/task.js
rm ./app/code/Wyomind/CronScheduler/Console/Command/Task/Show.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task.php
rmdir  ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Job
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing
rmdir  ./app/code/Wyomind/CronScheduler/Model/ResourceModel/Task
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing
rm ./app/code/Wyomind/Core/Controller/Activation/Webservice.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/css
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/js
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/layout
rmdir  ./app/code/Wyomind/CronScheduler/Controller/Adminhtml
rm ./app/code/Wyomind/Core/view/adminhtml/web/css/system.css
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task
rmdir  ./app/code/Wyomind/CronScheduler/Console/Command/Task
rm ./app/code/Wyomind/CronScheduler/etc/adminhtml/routes.xml
rmdir  ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer
rm ./app/code/Wyomind/CronScheduler/etc/adminhtml/system.xml
rm ./app/code/Wyomind/Core/Model/ResourceModel/Schedule.php
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Job
rm ./app/code/Wyomind/CronScheduler/Setup/InstallSchema.php
rmdir  ./app/code/Wyomind/CronScheduler/Console/Command/Job
rmdir  ./app/code/Wyomind/CronScheduler/Model/ResourceModel
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web
rm ./app/code/Wyomind/CronScheduler/etc/adminhtml/menu.xml
rm ./app/code/Wyomind/Core/Model/ResourceModel/Config.php
rm ./app/code/Wyomind/Core/Plugin/Config/Model/Config.php
rm ./app/code/Wyomind/CronScheduler/Helper/HeartBeat.php
rm ./app/code/Wyomind/CronScheduler/etc/cron_groups.xml
rmdir  ./app/code/Wyomind/CronScheduler/Console/Command
rmdir  ./app/code/Wyomind/CronScheduler/Ui/DataProvider
rm ./app/code/Wyomind/CronScheduler/Setup/Recurring.php
rm ./app/code/Wyomind/Core/Console/Command/Activate.php
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml
rmdir  ./app/code/Wyomind/Core/view/frontend/templates
rm ./app/code/Wyomind/CronScheduler/Cron/HeartBeat.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml
rmdir  ./app/code/Wyomind/CronScheduler/etc/adminhtml
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/css
rm ./app/code/Wyomind/Core/Console/Command/Status.php
rmdir  ./app/code/Wyomind/Core/Controller/Activation
rmdir  ./app/code/Wyomind/Core/view/adminhtml/layout
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component
rm ./app/code/Wyomind/CronScheduler/registration.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js
rm ./app/code/Wyomind/CronScheduler/Helper/Task.php
rm ./app/code/Wyomind/CronScheduler/etc/crontab.xml
rmdir  ./app/code/Wyomind/Core/view/frontend/layout
rm ./app/code/Wyomind/Core/etc/adminhtml/system.xml
rmdir  ./app/code/Wyomind/CronScheduler/Plugin/Cron
rm ./app/code/Wyomind/Core/etc/adminhtml/events.xml
rmdir  ./app/code/Wyomind/Core/Model/ResourceModel
rm ./app/code/Wyomind/CronScheduler/Helper/Job.php
rm ./app/code/Wyomind/Core/etc/frontend/routes.xml
rm ./app/code/Wyomind/Core/Model/Notifications.php
rm ./app/code/Wyomind/CronScheduler/Helper/Url.php
rmdir  ./app/code/Wyomind/CronScheduler/Controller
rm ./app/code/Wyomind/CronScheduler/etc/config.xml
rm ./app/code/Wyomind/CronScheduler/etc/module.xml
rm ./app/code/Wyomind/CronScheduler/i18n/fr_FR.csv
rm ./app/code/Wyomind/CronScheduler/i18n/en_US.csv
rmdir  ./app/code/Wyomind/Core/Plugin/Config/Model
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web
rm ./app/code/Wyomind/CronScheduler/composer.json
rm ./app/code/Wyomind/CronScheduler/etc/acl.xml
rm ./app/code/Wyomind/CronScheduler/LICENSE.TXT
rm ./app/code/Wyomind/Core/Block/Webservice.php
rmdir  ./app/code/Wyomind/CronScheduler/Console
rm ./app/code/Wyomind/Core/etc/adminhtml/di.xml
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml
rmdir  ./app/code/Wyomind/CronScheduler/Plugin
rm ./app/code/Wyomind/CronScheduler/etc/di.xml
rmdir  ./app/code/Wyomind/Core/Console/Command
rmdir  ./app/code/Wyomind/CronScheduler/Helper
rmdir  ./app/code/Wyomind/CronScheduler/Block
rm ./app/code/Wyomind/Core/Logger/Handler.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml
rm ./app/code/Wyomind/Core/Helper/License.php
rmdir  ./app/code/Wyomind/CronScheduler/Setup
rmdir  ./app/code/Wyomind/CronScheduler/Model
rmdir  ./app/code/Wyomind/Core/etc/adminhtml
rm ./app/code/Wyomind/Core/Logger/Logger.php
rmdir  ./app/code/Wyomind/Core/Plugin/Config
rmdir  ./app/code/Wyomind/CronScheduler/Cron
rmdir  ./app/code/Wyomind/CronScheduler/view
rmdir  ./app/code/Wyomind/CronScheduler/i18n
rmdir  ./app/code/Wyomind/Core/view/frontend
rmdir  ./app/code/Wyomind/Core/etc/frontend
rm ./app/code/Wyomind/Core/registration.php
rmdir  ./app/code/Wyomind/CronScheduler/etc
rm ./app/code/Wyomind/Core/Helper/Data.php
rm ./app/code/Wyomind/Core/Helper/Core.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui
rm ./app/code/Wyomind/Core/Model/Feed.php
rm ./app/code/Wyomind/Core/etc/module.xml
rm ./app/code/Wyomind/Core/etc/config.xml
rmdir  ./app/code/Wyomind/Core/Controller
rm ./app/code/Wyomind/Core/composer.json
rmdir  ./app/code/Wyomind/CronScheduler
rmdir  ./app/code/Wyomind/Core/Observer
rmdir  ./app/code/Wyomind/Core/Console
rm ./app/code/Wyomind/Core/LICENSE.TXT
rmdir  ./app/code/Wyomind/Core/Helper
rm ./app/code/Wyomind/Core/etc/di.xml
rmdir  ./app/code/Wyomind/Core/Plugin
rmdir  ./app/code/Wyomind/Core/Logger
rmdir  ./app/code/Wyomind/Core/Model
rmdir  ./app/code/Wyomind/Core/Block
rmdir  ./app/code/Wyomind/Core/view
rmdir  ./app/code/Wyomind/Core/etc
rmdir  ./app/code/Wyomind/Core
rmdir  ./app/code/Wyomind
rmdir  ./app/code
rmdir  ./app